# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import shopping_platform_pb2 as shopping__platform__pb2


class SellerServiceStub(object):
    """Define services
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.registerSeller = channel.unary_unary(
                '/SellerService/registerSeller',
                request_serializer=shopping__platform__pb2.RegisterSellerRequest.SerializeToString,
                response_deserializer=shopping__platform__pb2.RegisterSellerResponse.FromString,
                )
        self.sellItem = channel.unary_unary(
                '/SellerService/sellItem',
                request_serializer=shopping__platform__pb2.SellItemRequest.SerializeToString,
                response_deserializer=shopping__platform__pb2.SellItemResponse.FromString,
                )
        self.updateItem = channel.unary_unary(
                '/SellerService/updateItem',
                request_serializer=shopping__platform__pb2.UpdateItemRequest.SerializeToString,
                response_deserializer=shopping__platform__pb2.UpdateItemResponse.FromString,
                )
        self.deleteItem = channel.unary_unary(
                '/SellerService/deleteItem',
                request_serializer=shopping__platform__pb2.DeleteItemRequest.SerializeToString,
                response_deserializer=shopping__platform__pb2.DeleteItemResponse.FromString,
                )
        self.displaySellerItems = channel.unary_unary(
                '/SellerService/displaySellerItems',
                request_serializer=shopping__platform__pb2.DisplaySellerItemsRequest.SerializeToString,
                response_deserializer=shopping__platform__pb2.DisplaySellerItemsResponse.FromString,
                )


class SellerServiceServicer(object):
    """Define services
    """

    def registerSeller(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sellItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def displaySellerItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SellerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'registerSeller': grpc.unary_unary_rpc_method_handler(
                    servicer.registerSeller,
                    request_deserializer=shopping__platform__pb2.RegisterSellerRequest.FromString,
                    response_serializer=shopping__platform__pb2.RegisterSellerResponse.SerializeToString,
            ),
            'sellItem': grpc.unary_unary_rpc_method_handler(
                    servicer.sellItem,
                    request_deserializer=shopping__platform__pb2.SellItemRequest.FromString,
                    response_serializer=shopping__platform__pb2.SellItemResponse.SerializeToString,
            ),
            'updateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.updateItem,
                    request_deserializer=shopping__platform__pb2.UpdateItemRequest.FromString,
                    response_serializer=shopping__platform__pb2.UpdateItemResponse.SerializeToString,
            ),
            'deleteItem': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteItem,
                    request_deserializer=shopping__platform__pb2.DeleteItemRequest.FromString,
                    response_serializer=shopping__platform__pb2.DeleteItemResponse.SerializeToString,
            ),
            'displaySellerItems': grpc.unary_unary_rpc_method_handler(
                    servicer.displaySellerItems,
                    request_deserializer=shopping__platform__pb2.DisplaySellerItemsRequest.FromString,
                    response_serializer=shopping__platform__pb2.DisplaySellerItemsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SellerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SellerService(object):
    """Define services
    """

    @staticmethod
    def registerSeller(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SellerService/registerSeller',
            shopping__platform__pb2.RegisterSellerRequest.SerializeToString,
            shopping__platform__pb2.RegisterSellerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sellItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SellerService/sellItem',
            shopping__platform__pb2.SellItemRequest.SerializeToString,
            shopping__platform__pb2.SellItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def updateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SellerService/updateItem',
            shopping__platform__pb2.UpdateItemRequest.SerializeToString,
            shopping__platform__pb2.UpdateItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SellerService/deleteItem',
            shopping__platform__pb2.DeleteItemRequest.SerializeToString,
            shopping__platform__pb2.DeleteItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def displaySellerItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SellerService/displaySellerItems',
            shopping__platform__pb2.DisplaySellerItemsRequest.SerializeToString,
            shopping__platform__pb2.DisplaySellerItemsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class BuyerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.searchItem = channel.unary_unary(
                '/BuyerService/searchItem',
                request_serializer=shopping__platform__pb2.SearchItemRequest.SerializeToString,
                response_deserializer=shopping__platform__pb2.SearchItemResponse.FromString,
                )
        self.buyItem = channel.unary_unary(
                '/BuyerService/buyItem',
                request_serializer=shopping__platform__pb2.BuyItemRequest.SerializeToString,
                response_deserializer=shopping__platform__pb2.BuyItemResponse.FromString,
                )
        self.addToWishList = channel.unary_unary(
                '/BuyerService/addToWishList',
                request_serializer=shopping__platform__pb2.AddToWishListRequest.SerializeToString,
                response_deserializer=shopping__platform__pb2.AddToWishListResponse.FromString,
                )
        self.rateItem = channel.unary_unary(
                '/BuyerService/rateItem',
                request_serializer=shopping__platform__pb2.RateItemRequest.SerializeToString,
                response_deserializer=shopping__platform__pb2.RateItemResponse.FromString,
                )


class BuyerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def searchItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def buyItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def addToWishList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def rateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BuyerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'searchItem': grpc.unary_unary_rpc_method_handler(
                    servicer.searchItem,
                    request_deserializer=shopping__platform__pb2.SearchItemRequest.FromString,
                    response_serializer=shopping__platform__pb2.SearchItemResponse.SerializeToString,
            ),
            'buyItem': grpc.unary_unary_rpc_method_handler(
                    servicer.buyItem,
                    request_deserializer=shopping__platform__pb2.BuyItemRequest.FromString,
                    response_serializer=shopping__platform__pb2.BuyItemResponse.SerializeToString,
            ),
            'addToWishList': grpc.unary_unary_rpc_method_handler(
                    servicer.addToWishList,
                    request_deserializer=shopping__platform__pb2.AddToWishListRequest.FromString,
                    response_serializer=shopping__platform__pb2.AddToWishListResponse.SerializeToString,
            ),
            'rateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.rateItem,
                    request_deserializer=shopping__platform__pb2.RateItemRequest.FromString,
                    response_serializer=shopping__platform__pb2.RateItemResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BuyerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BuyerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def searchItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BuyerService/searchItem',
            shopping__platform__pb2.SearchItemRequest.SerializeToString,
            shopping__platform__pb2.SearchItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def buyItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BuyerService/buyItem',
            shopping__platform__pb2.BuyItemRequest.SerializeToString,
            shopping__platform__pb2.BuyItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def addToWishList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BuyerService/addToWishList',
            shopping__platform__pb2.AddToWishListRequest.SerializeToString,
            shopping__platform__pb2.AddToWishListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def rateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BuyerService/rateItem',
            shopping__platform__pb2.RateItemRequest.SerializeToString,
            shopping__platform__pb2.RateItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class MarketServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.notifyClient = channel.unary_unary(
                '/MarketService/notifyClient',
                request_serializer=shopping__platform__pb2.NotifyClientRequest.SerializeToString,
                response_deserializer=shopping__platform__pb2.NotifyClientResponse.FromString,
                )
        self.sellItem = channel.unary_unary(
                '/MarketService/sellItem',
                request_serializer=shopping__platform__pb2.SellItemRequest.SerializeToString,
                response_deserializer=shopping__platform__pb2.SellItemResponse.FromString,
                )
        self.displaySellerItems = channel.unary_unary(
                '/MarketService/displaySellerItems',
                request_serializer=shopping__platform__pb2.DisplaySellerItemsRequest.SerializeToString,
                response_deserializer=shopping__platform__pb2.DisplaySellerItemsResponse.FromString,
                )


class MarketServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def notifyClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sellItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def displaySellerItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'notifyClient': grpc.unary_unary_rpc_method_handler(
                    servicer.notifyClient,
                    request_deserializer=shopping__platform__pb2.NotifyClientRequest.FromString,
                    response_serializer=shopping__platform__pb2.NotifyClientResponse.SerializeToString,
            ),
            'sellItem': grpc.unary_unary_rpc_method_handler(
                    servicer.sellItem,
                    request_deserializer=shopping__platform__pb2.SellItemRequest.FromString,
                    response_serializer=shopping__platform__pb2.SellItemResponse.SerializeToString,
            ),
            'displaySellerItems': grpc.unary_unary_rpc_method_handler(
                    servicer.displaySellerItems,
                    request_deserializer=shopping__platform__pb2.DisplaySellerItemsRequest.FromString,
                    response_serializer=shopping__platform__pb2.DisplaySellerItemsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MarketService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MarketService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def notifyClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MarketService/notifyClient',
            shopping__platform__pb2.NotifyClientRequest.SerializeToString,
            shopping__platform__pb2.NotifyClientResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sellItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MarketService/sellItem',
            shopping__platform__pb2.SellItemRequest.SerializeToString,
            shopping__platform__pb2.SellItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def displaySellerItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MarketService/displaySellerItems',
            shopping__platform__pb2.DisplaySellerItemsRequest.SerializeToString,
            shopping__platform__pb2.DisplaySellerItemsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
