# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mapreduce.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmapreduce.proto\x12\tmapreduce\"\x1d\n\x0cShuffleInput\x12\r\n\x05MyNum\x18\x01 \x01(\x03\" \n\x0fShuffleResponse\x12\r\n\x05pairs\x18\x01 \x03(\t\"-\n\nSAndSInput\x12\x10\n\x08MapPorts\x18\x01 \x03(\x03\x12\r\n\x05MyNum\x18\x02 \x01(\x03\"\x1f\n\rSAndSResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\r\n\x0bReduceInput\" \n\x0eReduceResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x1b\n\x0ePartitionInput\x12\t\n\x01R\x18\x01 \x01(\t\"#\n\x11PartitionResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\"\n\rInputLocation\x12\x11\n\tlocations\x18\x01 \x03(\t\"\x1d\n\x0bMapResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"4\n\x0cInputMessage\x12\x11\n\tlocations\x18\x01 \x03(\t\x12\x11\n\tcentroids\x18\x02 \x03(\x02\x32\xd5\x01\n\rMapperService\x12>\n\nperformMap\x12\x18.mapreduce.InputLocation\x1a\x16.mapreduce.MapResponse\x12\x44\n\tpartition\x12\x19.mapreduce.PartitionInput\x1a\x1c.mapreduce.PartitionResponse\x12>\n\x07shuffle\x12\x17.mapreduce.ShuffleInput\x1a\x1a.mapreduce.ShuffleResponse2\x97\x01\n\x0eReducerService\x12\x41\n\x0eShuffleAndSort\x12\x15.mapreduce.SAndSInput\x1a\x18.mapreduce.SAndSResponse\x12\x42\n\rperformReduce\x12\x16.mapreduce.ReduceInput\x1a\x19.mapreduce.ReduceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mapreduce_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SHUFFLEINPUT']._serialized_start=30
  _globals['_SHUFFLEINPUT']._serialized_end=59
  _globals['_SHUFFLERESPONSE']._serialized_start=61
  _globals['_SHUFFLERESPONSE']._serialized_end=93
  _globals['_SANDSINPUT']._serialized_start=95
  _globals['_SANDSINPUT']._serialized_end=140
  _globals['_SANDSRESPONSE']._serialized_start=142
  _globals['_SANDSRESPONSE']._serialized_end=173
  _globals['_REDUCEINPUT']._serialized_start=175
  _globals['_REDUCEINPUT']._serialized_end=188
  _globals['_REDUCERESPONSE']._serialized_start=190
  _globals['_REDUCERESPONSE']._serialized_end=222
  _globals['_PARTITIONINPUT']._serialized_start=224
  _globals['_PARTITIONINPUT']._serialized_end=251
  _globals['_PARTITIONRESPONSE']._serialized_start=253
  _globals['_PARTITIONRESPONSE']._serialized_end=288
  _globals['_INPUTLOCATION']._serialized_start=290
  _globals['_INPUTLOCATION']._serialized_end=324
  _globals['_MAPRESPONSE']._serialized_start=326
  _globals['_MAPRESPONSE']._serialized_end=355
  _globals['_INPUTMESSAGE']._serialized_start=357
  _globals['_INPUTMESSAGE']._serialized_end=409
  _globals['_MAPPERSERVICE']._serialized_start=412
  _globals['_MAPPERSERVICE']._serialized_end=625
  _globals['_REDUCERSERVICE']._serialized_start=628
  _globals['_REDUCERSERVICE']._serialized_end=779
# @@protoc_insertion_point(module_scope)
